name: Code Quality and Linting

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort mypy

    - name: Check code formatting with Black
      run: |
        black --check --diff --color .

    - name: Check import sorting with isort
      run: |
        isort --check-only --diff --color .

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Type checking with mypy (optional)
      run: |
        mypy . --ignore-missing-imports --exclude migrations
      continue-on-error: true  # No fallar el build por type errors

    - name: Security check with bandit
      run: |
        pip install bandit
        bandit -r . -x tests,migrations,venv
      continue-on-error: true

    - name: Check for Django security issues
      env:
        DJANGO_SETTINGS_MODULE: config.settings_ci
      run: |
        python manage.py check --deploy --settings=config.settings_ci
      continue-on-error: true

  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-